kind: ConfigMap
apiVersion: v1
metadata:
  name: dvote-configmap
data:
  domain: "vocstack.local"
  frontend_nginx_default: |
    server {
      listen       80;
      listen  [::]:80;
      server_name  _;

      location / {
          root   /var/www/html;
          index  index.html index.htm;
          add_header 'Access-Control-Allow-Origin' '*';
      }

      error_page   500 502 503 504  /50x.html;
      location = /50x.html {
          root   /var/www/html;
      }
    }

